In [ ]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [ ]:
df = pd.read_csv('student.csv')
df.head(3)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811

In [ ]:
df.columns=['sinif','saat','puan']
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [ ]:
y = df[["puan"]]
x = df[["sinif","saat"]]

In [ ]:
lm = LinearRegression()
model = lm.fit(x,y)

y = ax + b


In [ ]:
model.coef_ #katsayı  a1.x1  a2.x2 bulur

array([[1.86405074, 5.39917879]])

In [ ]:
model.intercept_ #sabit yani formüldeki b yi buluyor

array([-7.45634623])

In [ ]:
model.predict([[4,3]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[16.1973931]])

In [ ]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [ ]:
model.predict([[3,4.508]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[22.47530397]])

In [ ]:
s1 = model.predict([[3,4.508]])[0][0]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [ ]:
-(19.202-s1)/19.202

np.float64(0.17046682485899442)

In [ ]:
model.score(x,y)

0.9403656320238896